$(function() {
	var brnh = [
		'TUP-THE CHENNAI SILKS',
		'CBE-THE CHENNAI SILKS',
		'ERD-THE CHENNAI SILKS',
		'CHN-THE CHENNAI SILKS',
		'TRY-THE CHENNAI SILKS',
		'CB2-THE CHENNAI SILKS',
		'CB3-THE CHENNAI SILKS',
		'SHREE NANDHI SILKS P LTD',
		'EKM-THE CHENNAI SILKS',
		'TNV-THE CHENNAI SILKS',
		'VLR-THE CHENNAI SILKS',
		'SLM-THE CHENNAI SILKS',
		'MDU-THE CHENNAI SILKS',
		'VPM - THE CHENNAI SILKS',
		'VCY - THE CHENNAI SILKS',
		'HSR - THE CHENNAI SILKS',
		'CWH-THE CHENNAI SILKS',
		'ONL-THE CHENNAI SILKS',
		'TCS CORP',
		'CBE AIR-THE CHENNAI SILKS',
		'HYD AIR - THE CHENNAI SILKS',
		'TRY AIR - THE CHENNAI SILKS',
		'SAMPLE - CORP',
		'KASTHURIBAI KHADI VASTRALAYAM',
		'U6-THE UNIT OF THE CHENNAI SILKS',
		'MDU AIR - THE CHENNAI SILKS',
		'MUM AIR - THE CHENNAI SILKS',
		'THE CHENNAI SILKS',
		 ];
		 $( '#brn' ).autocomplete({
		source: brnh});
		 });
		
		$(function() {
	var secgrp = [
		'1-BOYS READYMADE',
		'2-GIRLS READYMADE',
		'3-INFANTS',
		'4-SALWAR KAMEEZ',
		'5-MENS FORMAL SHIRTS',
		'6-MENS TROUSERS',
		'7-MENS ETHNIC',
		'8-SUITING',
		'9-SILKS',
		'10-FANCY SAREES',
		'11-FANCY SILK',
		'12-FANCY ART SAREES',
		'13-SAREES',
		'14-COTTON SAREES',
		'15-DRESS MATERIAL',
		'16-MATCHING',
		'17-L.I.GARMENTS',
		'19-HANDLOOM',
		'26-TEENAGE GIRLS',
		'27-SHIRTING',
		'28-CUTPIECE',
		'29-MENS T-SHIRTS',
		'31-MENS CASUAL SHIRTS',
		 ];
		 $( '#sec_grp' ).autocomplete({
		source: secgrp});
		 });